<?php
    $form = $this->form;
    $form->setAttribute('action',$this->url('editar',array('controller' => 'advocacia', 'action' => 'edit')));


    $form->prepare();

    echo $this->form()->openTag($form);
 ?>
    <div class="panel panel-default">
        <div class="panel-body">
            <?php  echo $this->formHidden($form->get('id')); ?>
            <?php  echo $this->formRow($form->get('nomecompleto')); ?>
            <?php  echo $this->formRow($form->get('RG')); ?>
            <?php  echo $this->formRow($form->get('cpfcnpj')); ?>
            <?php   echo $this->formRow($form->get('tipo')); ?>
            <?php  echo $this->formSubmit($form->get('submit')); ?>  
        </div>
    </div>
 <?php
    echo $this->form()->closeTag();
?>

